#!/usr/bin/env sh

# 确保脚本抛出遇到的错误
set -e

# 生成静态文件
yarn docs:build

# 进入生成的文件夹
cd docs/.vuepress/dist

echo 'idevebi.com' > CNAME

git init

git config user.name "壹刀流"
git config user.email "idevebi@163.com"

git add -A
git commit -m 'deploy'

git push -f git@github.com:IdEvEbI/daydayup.git master:gh-pages

cd -
